version: "3"

services:
    app:
        image: php:7.2
        volumes:
            - .:/app
        ports:
            - "${APP_PORT:-8000}:8000"
        working_dir: /app
        command: ["bin/console", "server:run", "0.0.0.0"]

    encore:
        image: node:10-alpine
        volumes:
            - .:/app
        ports:
            - "${DEV_SERVER_PORT:-8080}:8080"
        working_dir: /app
        command: ["npm", "install"]
        command: ["npm", "run", "watch", "--host=0.0.0.0"]